#include <stdio.h>

// Include the debugging utilities and declarations related to chunk operations.
#include "debug.h"

// Include the definitions for handling values and constants used in the chunk.
#include "value.h"

// Disassembles a given `Chunk` of bytecode, printing its instructions in a human-readable format.
// This function is used for debugging and understanding the bytecode generated by the compiler.
void disassembleChunk(Chunk* chunk, const char* name) {
  printf("== %s ==\n", name); // Print a header with the name of the chunk.

  for (int offset = 0; offset < chunk->count;) { // Iterate through all instructions in the chunk.
    offset = disassembleInstruction(chunk, offset); // Disassemble and print each instruction.
  }
}

// Handles the disassembly of instructions that involve constants.
// Prints the instruction name, the constant index, and the constant's value.
// This function is used for opcodes like `OP_CONSTANT` that require constant values.
static int constantInstruction(const char* name, Chunk* chunk, int offset) {
    uint8_t constant = chunk->code[offset + 1]; // Read the constant index from the bytecode.
    printf("%-16s %4d '", name, constant);      // Print the instruction name and constant index.
    printValue(chunk->constants.values[constant]); // Print the constant's value.
    printf("\n");
    return offset + 2; // Return the next instruction's offset (skip the constant index).
}

// Handles the disassembly of simple instructions that do not involve additional data.
// Prints the instruction name.
// This function is used for opcodes like `OP_RETURN`.
static int simpleInstruction(const char* name, int offset) {
  printf("%s\n", name); // Print the instruction name.
  return offset + 1;    // Return the next instruction's offset.
}

// Disassembles a single instruction at the given offset in the `Chunk` and prints it.
// This function identifies the opcode and calls the appropriate handler function.
// It is the core function for interpreting the bytecode for debugging purposes.
int disassembleInstruction(Chunk* chunk, int offset) {
  printf("%04d ", offset); // Print the instruction's offset in the chunk.

  // Print the line number, or a pipe if it is the same as the previous instruction.
  if (offset > 0 && chunk->lines[offset] == chunk->lines[offset - 1]) {
    printf("   | ");
  } else {
    printf("%4d ", chunk->lines[offset]);
  }

  uint8_t instruction = chunk->code[offset]; // Read the opcode at the current offset.
  switch (instruction) {
    case OP_CONSTANT:
        // Handle the `OP_CONSTANT` instruction, which involves a constant value.
        return constantInstruction("OP_CONSTANT", chunk, offset);
    case OP_RETURN:
        // Handle the `OP_RETURN` instruction, which is a simple instruction.
        return simpleInstruction("OP_RETURN", offset);
    default:
        // Handle unknown or invalid opcodes.
        printf("Unknown opcode %d\n", instruction);
        return offset + 1; // Skip the unknown instruction.
  }
}